### ISSUE TITLE
[Bug] Edit web  gives 500 error 

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp#2634]
### Describe the bug

Saving when LE is not enter might cause an 500 

### Tell us how to replicate the bug

See error log

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.6.0 beta

### Operating system

N/A

### Log capture

```shell
2022/05/30 15:42:06 [error] 654066#0: *96 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ArgumentCountError: _() expects exactly 1 argument, 2 given in /usr/local/hestia/web/edit/web/index.php:559
Stack trace:
#0 /usr/local/hestia/web/edit/web/index.php(559): _()
#1 {main}
  thrown in /usr/local/hestia/web/edit/web/index.php on line 559" while reading response header from upstream, client:, server: _, request: "POST /edit/web/?domain=&token=3c4eabc937d6faf16571066313a79f2d HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: ":8083", referrer: "https://:8083/edit/web/?domain=&token=3c4eabc937d6faf16571066313a79f2d"
2022/05/30 15:47:35 [error] 654066#0: *134 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ArgumentCountError: _() expects exactly 1 argument, 2 given in /usr/local/hestia/web/edit/web/index.php:705
Stack trace:
#0 /usr/local/hestia/web/edit/web/index.php(705): _()
#1 {main}
  thrown in /usr/local/hestia/web/edit/web/index.php on line 705" while reading response header from upstream, client:, server: _, request: "POST /edit/web/?domain=weetjes.net HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: ":8083", referrer: "https://:8083/edit/web/?domain="
```

**Comment by jaapmarcus** [comment]
```
2022/05/30 15:47:35 [error] 654066#0: *134 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ArgumentCountError: _() expects exactly 1 argument, 2 given in /usr/local/hestia/web/edit/web/index.php:705
Stack trace:
#0 /usr/local/hestia/web/edit/web/index.php(705): _()
#1 {main}
  thrown in /usr/local/hestia/web/edit/web/index.php on line 705" while reading response header from upstream, client: xxx, server: _, request: "POST /edit/web/?domain=xxx HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "xxx:8083", referrer: "https://xxx:8083/edit/web/?domain=xxx"
2022/05/30 16:45:29 [error] 654066#0: *143 FastCGI sent in stderr: "PHP message: PHP Warning:  Array to string conversion in /usr/local/hestia/web/src/app/System/HestiaApp.php on line 24PHP message: PHP Notice:  Error: file /tmp/hst.cV0xev was not copied in /usr/local/hestia/web/src/app/System/HestiaApp.php on line 40" while reading response header from upstream, client: xxx, server: _, request: "POST /add/webapp/?app=Wordpress&domain=xxx HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "xxx:8083", referrer: "https://xxx:8083/add/webapp/?app=Wordpress&domain=xxx"
2022/05/30 16:46:19 [error] 654066#0: *167 FastCGI sent in stderr: "PHP message: PHP Notice:  Error: WordPress files seem to already be present here.
Error: cmd exited with errors in /usr/local/hestia/web/src/app/System/HestiaApp.php on line 40" while reading response header from upstream, client: xxx, server: _, request: "POST /add/webapp/?app=Wordpress&domain=xxx HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "xxx:8083", referrer: "https://xxx:8083/add/webapp/?app=Wordpress&domain=xxx"
```
