### ISSUE TITLE
[Bug] 500 error with editing A records

### ISSUE THREAD

**Issue by ledoktre** [hestiacp/hestiacp#2658]
### Describe the bug

Whenever I try to edit an A record on Hestia 1.6.0, I receive a 500 error. If I edit any other type, works fine.

From the code, it looks like:

									<option value="A" <?php if ($v_type == 'A') echo selected; ?>>A</option>
									<option value="AAAA" <?php if ($v_type == 'AAAA') echo "selected"; ?>>AAAA</option>
									<option value="CAA" <?php if ($v_type == 'CAA') echo "selected"; ?>>CAA</option>

Line 75 needs quotes around selected?

Thanks

### Tell us how to replicate the bug

1. Open DNS tab, select a domain.
2. Edit an A record, throws a 500 error

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.6.0

### Operating system

Debian 11

### Log capture

```shell
thrown in /usr/local/hestia/web/templates/pages/edit_dns_rec.html on line 75" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: _, request: "GET /edit/dns/?domain=domain.com&record_id=84&token=XXXXXXXXXXXXXXXXXXXXXXX HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "dns.domain.com:8083", referrer: "https://dns.domain.com:8083/list/dns/?domain=domain.com&token=XXXXXXXXXXXXXXXXXXXXXXX"
2022/06/16 19:51:26 [error] 803#0: *24 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $v_twofa in /usr/local/hestia/web/login/index.php on line 191" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: _, request: "POST /login/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "dns.domain.com:8083", referrer: "https://dns.domain.com:8083/login/"
2022/06/16 19:51:27 [error] 803#0: *24 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $v_twofa in /usr/local/hestia/web/login/index.php on line 191" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: _, request: "POST /login/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "dns.domain.com:8083", referrer: "https://dns.domain.com:8083/login/"
2022/06/16 19:51:39 [error] 803#0: *31 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Undefined constant "selected" in /usr/local/hestia/web/templates/pages/edit_dns_rec.html:75
Stack trace:
#0 /usr/local/hestia/web/inc/main.php(181): include()
#1 /usr/local/hestia/web/edit/dns/index.php(220): render_page()
#2 {main}
  thrown in /usr/local/hestia/web/templates/pages/edit_dns_rec.html on line 75" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: _, request: "GET /edit/dns/?domain=domain.com&record_id=11&token=XXXXXXXXXXXXXXXXXXXXXXX HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "dns.domain.com:8083", referrer: "https://dns.domain.com:8083/list/dns/?domain=domain.com&token=XXXXXXXXXXXXXXXXXXXXXXX"
2022/06/16 19:54:33 [error] 803#0: *47 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Undefined constant "selected" in /usr/local/hestia/web/templates/pages/edit_dns_rec.html:75
Stack trace:
#0 /usr/local/hestia/web/inc/main.php(181): include()
#1 /usr/local/hestia/web/edit/dns/index.php(220): render_page()
#2 {main}
  thrown in /usr/local/hestia/web/templates/pages/edit_dns_rec.html on line 75" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: _, request: "GET /edit/dns/?domain=domain.com&record_id=10&token=XXXXXXXXXXXXXXXXXXXXXXX HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "dns.domain.com:8083", referrer: "https://dns.domain.com:8083/list/dns/?domain=domain.com&token=XXXXXXXXXXXXXXXXXXXXXXX"
2022/06/16 19:54:47 [error] 803#0: *43 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Undefined constant "selected" in /usr/local/hestia/web/templates/pages/edit_dns_rec.html:75
Stack trace:
#0 /usr/local/hestia/web/inc/main.php(181): include()
#1 /usr/local/hestia/web/edit/dns/index.php(220): render_page()
#2 {main}
  thrown in /usr/local/hestia/web/templates/pages/edit_dns_rec.html on line 75" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: _, request: "GET /edit/dns/?domain=domain.com&record_id=48&token=XXXXXXXXXXXXXXXXXXXXXXX HTTP/1.1", upstream: "fastcgi://unix:/var/run/hestia-php.sock:", host: "dns.domain.com:8083", referrer: "https://dns.domain.com:8083/list/dns/?domain=domain.com&token=XXXXXXXXXXXXXXXXXXXXXXX"
```

**Comment by jaapmarcus** [comment]
Merged 👍🏼
