### ISSUE TITLE
[Bug] File manager doesn't work

### ISSUE THREAD

**Issue by MrCyjaneK** [hestiacp/hestiacp#4071]
### Describe the bug

I've used v-import-directadmin to import few users, I have messed messed a bit with root's ssh keys and I did apt update && apt upgrade. I don't know if any of these actions could potentialy cause some damage to the file manager but except for this I didn't really do much to the server.

When I enter the file manager I see `unknown error` (just as described in the wiki) but given fix doesn't solve that for me.

I did try v-delete-sys-filemanager and adding it again, disabling it in plugins.

### Tell us how to replicate the bug

1. Open file manager

### Which components are affected by this bug?

Control Panel Web Interface, (Backend) Web Server (Nginx, Apache2)

### Hestia Control Panel Version

1.8.8

### Operating system

Debian GNU/Linux 12 (bookworm)

### Log capture

```shell
$ journalctl -feu ssh # capture only when refreshing the page with file manager open (after logging in as admin -> clicking testuser to login)
sshd[39207]: debug3: fd 5 is not O_NONBLOCK
sshd[39207]: debug1: Forked child 40327.
sshd[39207]: debug3: send_rexec_state: entering fd = 8 config len 3493
sshd[39207]: debug3: ssh_msg_send: type 0
sshd[39207]: debug3: send_rexec_state: done
sshd[40327]: debug3: oom_adjust_restore
sshd[40327]: debug1: Set /proc/self/oom_score_adj to 0
sshd[40327]: debug1: rexec start in 5 out 5 newsock 5 pipe 7 sock 8
sshd[40327]: debug1: inetd sockets after dupping: 4, 4
sshd[40327]: debug3: process_channel_timeouts: setting 0 timeouts
sshd[40327]: debug3: channel_clear_timeouts: clearing
sshd[40327]: Connection from 127.0.0.1 port 41902 on 127.0.0.1 port 22 rdomain ""
sshd[40327]: debug1: Local version string SSH-2.0-OpenSSH_9.2p1
sshd[40327]: debug1: Remote protocol version 2.0, remote software version phpseclib_2.0 (openssl, gmp)
sshd[40327]: debug1: compat_banner: no match: phpseclib_2.0 (openssl, gmp)
sshd[40327]: debug2: fd 4 setting O_NONBLOCK
sshd[40327]: debug3: ssh_sandbox_init: preparing seccomp filter sandbox
sshd[40327]: debug2: Network child is on pid 40328
sshd[40327]: debug3: preauth child monitor started
sshd[40327]: debug3: privsep user:group 101:65534 [preauth]
sshd[40327]: debug1: permanently_set_uid: 101/65534 [preauth]
sshd[40327]: debug3: ssh_sandbox_child: setting PR_SET_NO_NEW_PRIVS [preauth]
sshd[40327]: debug3: ssh_sandbox_child: attaching seccomp filter program [preauth]
sshd[40327]: debug1: list_hostkey_types: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
sshd[40327]: debug3: send packet: type 20 [preauth]
sshd[40327]: debug1: SSH2_MSG_KEXINIT sent [preauth]
sshd[40327]: debug3: receive packet: type 20 [preauth]
sshd[40327]: debug1: SSH2_MSG_KEXINIT received [preauth]
sshd[40327]: debug2: local server KEXINIT proposal [preauth]
sshd[40327]: debug2: KEX algorithms: sntrup761x25519-sha512@openssh.com,curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256 [preauth]
sshd[40327]: debug2: host key algorithms: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
sshd[40327]: debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com [preauth]
sshd[40327]: debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com [preauth]
sshd[40327]: debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preauth]
sshd[40327]: debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preauth]
sshd[40327]: debug2: compression ctos: none,zlib@openssh.com [preauth]
sshd[40327]: debug2: compression stoc: none,zlib@openssh.com [preauth]
sshd[40327]: debug2: languages ctos:  [preauth]
sshd[40327]: debug2: languages stoc:  [preauth]
sshd[40327]: debug2: first_kex_follows 0  [preauth]
sshd[40327]: debug2: reserved 0  [preauth]
sshd[40327]: debug2: peer client KEXINIT proposal [preauth]
sshd[40327]: debug2: KEX algorithms: diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1 [preauth]
sshd[40327]: debug2: host key algorithms: rsa-sha2-256,rsa-sha2-512,ssh-rsa,ssh-dss [preauth]
sshd[40327]: debug2: ciphers ctos: aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc,arcfour256,arcfour128,twofish128-ctr,twofish192-ctr,twofish256-ctr,twofish128-cbc,twofish192-cbc,twofish256-cbc,twofish-cbc,blowfish-ctr,blowfish-cbc,3des-ctr [preauth]
sshd[40327]: debug2: ciphers stoc: aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc,arcfour256,arcfour128,twofish128-ctr,twofish192-ctr,twofish256-ctr,twofish128-cbc,twofish192-cbc,twofish256-cbc,twofish-cbc,blowfish-ctr,blowfish-cbc,3des-ctr [preauth]
sshd[40327]: debug2: MACs ctos: hmac-sha2-256,hmac-sha1-96,hmac-sha1,hmac-md5-96,hmac-md5 [preauth]
sshd[40327]: debug2: MACs stoc: hmac-sha2-256,hmac-sha1-96,hmac-sha1,hmac-md5-96,hmac-md5 [preauth]
sshd[40327]: debug2: compression ctos: none [preauth]
sshd[40327]: debug2: compression stoc: none [preauth]
sshd[40327]: debug2: languages ctos:  [preauth]
sshd[40327]: debug2: languages stoc:  [preauth]
sshd[40327]: debug2: first_kex_follows 0  [preauth]
sshd[40327]: debug2: reserved 0  [preauth]
sshd[40327]: debug1: kex: algorithm: diffie-hellman-group-exchange-sha256 [preauth]
sshd[40327]: debug1: kex: host key algorithm: rsa-sha2-256 [preauth]
sshd[40327]: debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha2-256 compression: none [preauth]
sshd[40327]: debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256 compression: none [preauth]
sshd[40327]: debug1: expecting SSH2_MSG_KEX_DH_GEX_REQUEST [preauth]
sshd[40327]: debug3: receive packet: type 34 [preauth]
sshd[40327]: debug1: SSH2_MSG_KEX_DH_GEX_REQUEST received [preauth]
sshd[40327]: debug3: mm_request_send: entering, type 0 [preauth]
sshd[40327]: debug3: mm_choose_dh: waiting for MONITOR_ANS_MODULI [preauth]
sshd[40327]: debug3: mm_request_receive_expect: entering, type 1 [preauth]
sshd[40327]: debug3: mm_request_receive: entering [preauth]
sshd[40327]: debug3: mm_request_receive: entering
sshd[40327]: debug3: monitor_read: checking request 0
sshd[40327]: debug3: mm_answer_moduli: got parameters: 2048 2048 4096
sshd[40327]: debug3: mm_request_send: entering, type 1
sshd[40327]: debug2: monitor_read: 0 used once, disabling now
sshd[40327]: debug3: mm_choose_dh: remaining 0 [preauth]
sshd[40327]: debug1: SSH2_MSG_KEX_DH_GEX_GROUP sent [preauth]
sshd[40327]: debug3: send packet: type 31 [preauth]
sshd[40327]: debug2: bits set: 1032/2048 [preauth]
sshd[40327]: debug1: expecting SSH2_MSG_KEX_DH_GEX_INIT [preauth]
sshd[40327]: debug3: receive packet: type 32 [preauth]
sshd[40327]: debug1: SSH2_MSG_KEX_DH_GEX_INIT received [preauth]
sshd[40327]: debug2: bits set: 1042/2048 [preauth]
sshd[40327]: debug3: mm_sshkey_sign: entering [preauth]
sshd[40327]: debug3: mm_request_send: entering, type 6 [preauth]
sshd[40327]: debug3: mm_sshkey_sign: waiting for MONITOR_ANS_SIGN [preauth]
sshd[40327]: debug3: mm_request_receive_expect: entering, type 7 [preauth]
sshd[40327]: debug3: mm_request_receive: entering [preauth]
sshd[40327]: debug3: mm_request_receive: entering
sshd[40327]: debug3: monitor_read: checking request 6
sshd[40327]: debug3: mm_answer_sign: entering
sshd[40327]: debug3: mm_answer_sign: rsa-sha2-256 KEX signature len=404
sshd[40327]: debug3: mm_request_send: entering, type 7
sshd[40327]: debug2: monitor_read: 6 used once, disabling now
sshd[40327]: debug3: send packet: type 33 [preauth]
sshd[40327]: debug3: send packet: type 21 [preauth]
sshd[40327]: debug2: ssh_set_newkeys: mode 1 [preauth]
sshd[40327]: debug1: rekey out after 4294967296 blocks [preauth]
sshd[40327]: debug1: SSH2_MSG_NEWKEYS sent [preauth]
sshd[40327]: debug1: expecting SSH2_MSG_NEWKEYS [preauth]
sshd[40327]: debug3: receive packet: type 21 [preauth]
sshd[40327]: debug1: SSH2_MSG_NEWKEYS received [preauth]
sshd[40327]: debug2: ssh_set_newkeys: mode 0 [preauth]
sshd[40327]: debug1: rekey in after 4294967296 blocks [preauth]
sshd[40327]: debug1: KEX done [preauth]
sshd[40327]: debug3: receive packet: type 5 [preauth]
sshd[40327]: debug3: send packet: type 6 [preauth]
sshd[40327]: debug3: receive packet: type 50 [preauth]
sshd[40327]: debug1: userauth-request for user testuser service ssh-connection method none [preauth]
sshd[40327]: debug1: attempt 0 failures 0 [preauth]
sshd[40327]: debug3: mm_getpwnamallow: entering [preauth]
sshd[40327]: debug3: mm_request_send: entering, type 8 [preauth]
sshd[40327]: debug3: mm_getpwnamallow: waiting for MONITOR_ANS_PWNAM [preauth]
sshd[40327]: debug3: mm_request_receive_expect: entering, type 9 [preauth]
sshd[40327]: debug3: mm_request_receive: entering [preauth]
sshd[40327]: debug3: mm_request_receive: entering
sshd[40327]: debug3: monitor_read: checking request 8
sshd[40327]: debug3: mm_answer_pwnamallow: entering
sshd[40327]: debug2: parse_server_config_depth: config reprocess config len 3493
sshd[40327]: debug2: parse_server_config_depth: config  len 0
sshd[40327]: debug3: checking match for 'User [REDACTED],testuser' user testuser host 127.0.0.1 addr 127.0.0.1 laddr 127.0.0.1 lport 22
sshd[40327]: debug1: user testuser matched 'User [REDACTED],testuser' at line 128
sshd[40327]: debug3: match found
sshd[40327]: debug3: reprocess config:129 setting ChrootDirectory %h
sshd[40327]: debug3: reprocess config:130 setting X11Forwarding no
sshd[40327]: debug3: reprocess config:131 setting AllowTCPForwarding no
sshd[40327]: debug3: reprocess config:132 setting ForceCommand internal-sftp
sshd[40327]: debug3: mm_answer_pwnamallow: sending MONITOR_ANS_PWNAM: 1
sshd[40327]: debug3: mm_request_send: entering, type 9
sshd[40327]: debug2: monitor_read: 8 used once, disabling now
sshd[40327]: debug3: process_channel_timeouts: setting 0 timeouts [preauth]
sshd[40327]: debug3: channel_clear_timeouts: clearing [preauth]
sshd[40327]: debug2: input_userauth_request: setting up authctxt for testuser [preauth]
sshd[40327]: debug3: mm_start_pam entering [preauth]
sshd[40327]: debug3: mm_request_send: entering, type 100 [preauth]
sshd[40327]: debug3: mm_inform_authserv: entering [preauth]
sshd[40327]: debug3: mm_request_send: entering, type 4 [preauth]
sshd[40327]: debug2: input_userauth_request: try method none [preauth]
sshd[40327]: debug3: user_specific_delay: user specific delay 0.000ms [preauth]
sshd[40327]: debug3: ensure_minimum_time_since: elapsed 2.727ms, delaying 5.567ms (requested 8.294ms) [preauth]
sshd[40327]: debug3: mm_request_receive: entering
sshd[40327]: debug3: monitor_read: checking request 100
sshd[40327]: debug1: PAM: initializing for "testuser"
sshd[40327]: debug1: PAM: setting PAM_RHOST to "127.0.0.1"
sshd[40327]: debug1: PAM: setting PAM_TTY to "ssh"
sshd[40327]: debug2: monitor_read: 100 used once, disabling now
sshd[40327]: debug3: userauth_finish: failure partial=0 next methods="publickey,password" [preauth]
sshd[40327]: debug3: send packet: type 51 [preauth]
sshd[40327]: debug3: receive packet: type 50 [preauth]
sshd[40327]: debug1: userauth-request for user testuser service ssh-connection method none [preauth]
sshd[40327]: debug1: attempt 1 failures 0 [preauth]
sshd[40327]: debug3: authmethod_lookup: method none not enabled [preauth]
sshd[40327]: debug3: user_specific_delay: user specific delay 0.000ms [preauth]
sshd[40327]: debug3: ensure_minimum_time_since: elapsed 0.032ms, delaying 8.263ms (requested 8.294ms) [preauth]
sshd[40327]: debug3: mm_request_receive: entering
sshd[40327]: debug3: monitor_read: checking request 4
sshd[40327]: debug3: mm_answer_authserv: service=ssh-connection, style=, role=
sshd[40327]: debug2: monitor_read: 4 used once, disabling now
sshd[40327]: debug3: userauth_finish: failure partial=0 next methods="publickey,password" [preauth]
sshd[40327]: debug3: send packet: type 51 [preauth]
sshd[40327]: debug3: receive packet: type 1 [preauth]
sshd[40327]: Received disconnect from 127.0.0.1 port 41902:11:  [preauth]
sshd[40327]: Disconnected from authenticating user testuser 127.0.0.1 port 41902 [preauth]
sshd[40327]: debug1: do_cleanup [preauth]
sshd[40327]: debug3: PAM: sshpam_thread_cleanup entering [preauth]
sshd[40327]: debug1: monitor_read_log: child log fd closed
sshd[40327]: debug3: mm_request_receive: entering
sshd[40327]: debug1: do_cleanup
sshd[40327]: debug1: PAM: cleanup
sshd[40327]: debug3: PAM: sshpam_thread_cleanup entering
sshd[40327]: debug1: Killing privsep child 40328
sshd[40327]: debug1: audit_event: unhandled event 12

$ tail -f /var/log/hestia/nginx-error.log
2023/10/16 20:23:03 [error] 860#0: *118 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught League\Flysystem\Sftp\ConnectionErrorException: Could not login with username: testuser, host: 127.0.0.1 in /usr/local/hestia/web/fm/vendor/league/flysystem-sftp/src/SftpAdapter.php:244
Stack trace:
#0 /usr/local/hestia/web/fm/vendor/league/flysystem-sftp/src/SftpAdapter.php(207): League\Flysystem\Sftp\SftpAdapter->login()
#1 /usr/local/hestia/web/fm/vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php(650): League\Flysystem\Sftp\SftpAdapter->connect()
#2 /usr/local/hestia/web/fm/vendor/league/flysystem-sftp/src/SftpAdapter.php(360): League\Flysystem\Adapter\AbstractFtpAdapter->getConnection()
#3 /usr/local/hestia/web/fm/vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php(338): League\Flysystem\Sftp\SftpAdapter->listDirectoryContents()
#4 /usr/local/hestia/web/fm/vendor/league/flysystem/src/Filesystem.php(272): League\Flysystem\Adapter\AbstractFtpAdapter->listContents()
#5 /usr/local/hestia/web/fm/backend/Services/Storage/Filesystem.php(199): League\Fly" while reading response header from upstream, client: [REDACTED], server: _, request: "POST /fm/?r=/getdir HTTP/2.0", upstream: "fastcgi://unix:/run/hestia-php.sock:", host: "[REDACTED]:8083", referrer: "https://[REDACTED]:8083/fm/"

$ cat /etc/ssh/sshd_config | grep -E 'PasswordAuthentication|LoginGraceTime|Subsystem|DebianBanner'
LoginGraceTime 1m
PasswordAuthentication yes
DebianBanner no
Subsystem sftp internal-sftp

$ cat /etc/ssh/sshd_config # my extra stuff added on top of clean install
PubkeyAcceptedAlgorithms +ssh-rsa
HostkeyAlgorithms +ssh-rsa
```

**Comment by jaapmarcus** [comment]
What are the permissions of the .ssh folder and het-filemanager that created

**Comment by MrCyjaneK** [comment]
```bash
root@[REDACTED]:/home/testuser# ls -lahd .ssh
drwxr-xr-x 2 testuser testuser 4.0K Oct 16 20:21 .ssh
```
```
# find / -name 'het-filemanager' 2>/dev/null 
```

returned empty lines. I'm unsure what it is

**Comment by jaapmarcus** [comment]
>PubkeyAcceptedAlgorithms +ssh-rsa
>HostkeyAlgorithms +ssh-rsa

This might be the issue 

Check if hst-filemanager-key is created after you tried to login... 

Try logging via sftp with an ssh key and see if it works

[error] 860#0: *118 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught League\Flysystem\Sftp\ConnectionErrorException: Could not login with username: testuser, host: 127.0.0.1 in /usr/local/hestia/web/fm/vendor/league/flysystem-sftp/src/SftpAdapter.php:244

It seems that might be the issue

**Comment by MrCyjaneK** [comment]
```
$ ssh testuser@[REDACTED]
testuser@[REDACTED]'s password:
This service allows sftp connections only.
Connection to [REDACTED] closed.
```

The thing is I'm unable to open "Manage SSH Keys" it just redirects me to the '/list/web' page

![image](https://github.com/hestiacp/hestiacp/assets/20381330/6d6807bb-63f5-4f0a-9d1f-f95298bc6788)

**Comment by MrCyjaneK** [comment]
However - removing those lines (and restarting the server) didn't fix the issue ( but it breaks my sftp backup )

**Comment by jaapmarcus** [comment]
I have really no idea what could be wrong..

**Comment by MrCyjaneK** [comment]
@jaapmarcus I'll investigate it further and keep you updated.

**Comment by MrCyjaneK** [comment]
also I've missed this part: 

> Check if hst-filemanager-key is created after you tried to login...

There is also one important thing that I've done - that I did pretty early (and I think that file manager worked after this change).
So, to get a bit in depth of what is going wrong I've ran 
```
# bash -x $(which v-add-user-sftp-key) testuser
Error: Invalid private key file path
```

I can see that it expects it to be at a specific directory

```
+ PRVKEY_FILE=/home/testuser/.ssh/hst-filemanager-key
+ PUBKEY_FILE=/home/testuser/.ssh/hst-filemanager-key.pub
+ AUTHKEY_FILE=/home/testuser/.ssh/authorized_keys
++ readlink -f /home/testuser/.ssh/hst-filemanager-key
++ egrep '^/home/testuser/.ssh/'
```
but it is not..

```
#  readlink -f /home/testuser/.ssh/hst-filemanager-key
/mnt/volume_fsn1_1/home/testuser/.ssh/hst-filemanager-key
```

Because I've moved my home dir to save space on root fs.

**Comment by jaapmarcus** [comment]
Mount the drive instead of a symbolic links and it should work fine ...

**Comment by MrCyjaneK** [comment]
yeah ^^ sorry for bothering you and thanks for help!
